# Generated by Django 4.1.5 on 2023-01-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.IntegerField(choices=[(1, 'Developers'), (2, 'IT & Product support'), (3, 'Product management'), (4, 'Project leaders'), (5, 'QA'), (6, 'IT infrastructure'), (7, 'Finance & Legal'), (8, 'Marketing'), (9, 'Sell & Solution consulting'), (10, 'HR & people support'), (11, 'Innonspot'), (12, 'Viima'), (13, 'Administration')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='office',
            field=models.IntegerField(choices=[(1, 'Bonn'), (2, 'Cologne'), (3, 'Frankfurt'), (4, 'Other in germany'), (5, 'USA'), (6, 'France'), (7, 'Other')]),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
