# Generated by Django 4.1.5 on 2023-01-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_department_alter_customuser_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='family',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
