# Generated by Django 4.1.5 on 2023-01-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_customuser_first_name_customuser_last_name'),
        ('Office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.customuser')),
            ],
        ),
    ]
