# Generated by Django 4.1.5 on 2023-01-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_customuser_department_alter_customuser_email_and_more'),
        ('Office', '0003_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.customuser')),
            ],
        ),
    ]
