# Generated by Django 4.1.5 on 2023-01-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0005_remove_bugreport_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorsdb',
            old_name='equipment',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='floorsdb',
            name='capacity',
        ),
    ]
